### ISSUE TITLE
Docker image and --stop 'height'

### ISSUE THREAD

**Issue by bkontur** [blockwatch-cc/tzindex#24]
Hello, how can I use docker image and tell him to `--stop height` ?
Is there any possibility?

my .drone.yml
```
  - name: tz-indexer-ocaml
    image: blockwatch/tzindex:latest
    user: root
    detach: false
    volumes:
      - name: indexer-data
        path: /data
    environment:
      TZ_RPC_HOST: ocaml-node-run
      TZ_RPC_PORT: 48732
      TZ_SERVER_ADDR: 0.0.0.0
      TZ_SERVER_PORT: 8007
      TZ_SERVER_CORS_ENABLE: true
      TZ_DATABASE_PATH: /data/index
      TZ_SNAPSHOT_PATH: /data/snapshots
```
